### ISSUE TITLE
Github content evaluation

### ISSUE THREAD

**Issue by floridop** [edutr98/MNXB01-TEAMF#8]
# Workplan
The Workplan is called Workflow and is neither a workplan nor a workflow,
but just a diary of what you decided.

# Changelog:
There is no changelog.

# README.md
The provided README.md is insufficent to evaluate any of the code.

In particular, the software requirements are totally unclear. 

You used a tool that was not part of the course, so you need to be
clear about details.

I am forced to comment each and every line to show how little information this conveys.

For starters, what is this garbage:
```
####################################################################################################################################################################
FILTERED DATA
2022.07.2+576

```

The section called "How to execute" tells everything but how to execute.

Maybe it should have been called "Prerequisites".

> 1. Be sure to have the last available version of R

I do not care about the last available version. I care about the version
you used. Which one is it?

>2. We recommend to use RStudio

Ok. For what?

>3. Please install the required libraries

And those are? How do I find out?

>4. Load the libraries

Where and when?

> 5. You are done!, the code is good to go.

Done with what? To go where?

Very disappointing.

The section "Content" actually tries to describe some processed datasets. It doesn't even present the full filename, nor which folder contains such files.

The section "Outputs" describes the files generated by the R code, and not the final output of the project.

Information how to run the rest of the code is totally absent.

# Code:

The folder organization is a bit misleading. 
The code folder does not contain all code, as the R code is stored in the `Final Filtered Data` and  `Old Filtered Data` .
But R code is _code_, right?

The `Data` folder contains some data, but some other data is in the `Final Filtered Data`.

So what's in the `Data` folder? Is that "final"?

## Data_Filtered_GREA_LESS.R and Data_Filtered_Hours.R

I managed to setup R and loaded all the libraries that R could
detect. It took quite some time.

To do that:
1. open the Lunarc Desktop.
2. Open RStudio by navigating the menu Applications -> Lunarc Applications On-Demand -> Development -> Rstudio (choose a suitable version. I chose Rstudio 2021.09.01 (CPU) ) ![Rstudio](https://user-images.githubusercontent.com/2563123/203609736-1fdca55b-217f-448d-863c-fcb4975b5c60.png)
3. In the dialog that appears:
  1. Select a walltime of `00:60:00`
  2. click on the three dots near walltime. Select `tasks per node = 1` and press OK
4. Project: select `lu2021-7-65` (our course allocation)
5. Click on Start ![Rsetallocation](https://user-images.githubusercontent.com/2563123/203609742-0239fa9b-beed-48f3-93af-fb4f7f46e5f9.png)

R and Rstudio will now run in one of the computing nodes for 60 minutes. After that time the job will be killed. If you want to see the allocation process click on `More...`. You will see it looks like what the SLURM tutorial has shown.

I noticed the code refers to windows paths to xlsx files. 
Such files are not provided in the project so nothing could be tested.

Such fact that one had to hardcode full path filenames was not mentioned 
anywhere in the documentation.

I am not an R expert but for what I can see there is a lot of repetition
due to the fact that variables are used to store information and no real
generic reusable datamodel was implemented. But it might be due to my limited R knowledge.

ACTION: provide the input xlsx files to test this code.

## content of `code` folder

The `.C` scripts are basic ROOT scripts. At a quick glance I have no
comments, however, I have no idea how to run and reproduce since
there is no mention in the `README.md` 
The hardcoded files in the script do not match anything in the uploaded repository, 
so I really can't test/tell whether this code works.

ACTION: 
  - Provide missing input files (xlsx used in the R code and .txt used in ROOT)
  - Clarify in the README.md how to run the ROOT part

# Summary

The provided code is totally insufficient to assess the quality of any
of the work done. Please take the actions listed above.

**Comment by edutr98** [comment]
Dear Florido,

Thanks for your feedback, we will work on everything you told us.

Kind regards,

Team F

**Comment by sergio2momo** [comment]
Dear Florido, 
The code in R could "repetitive" but this is because of the way the dplyr library works. 
As you can notice, we used the mutate, group_by and filter functions each time because we are changing the original data set (UmeaData_Fil) | (FalsterboData_Fil) and the output parameters for each function can not be stored in a variable. 

Hope this brief explanation solved your doubts, let us now if it is not the case.

**Comment by floridop** [comment]
Hi @sergio2momo @geppisan @edutr98,
Thanks for this input. It's a lot of detail in the README, I just wanted a practical description of how to run your code.
I tried to follow the instructions and by  what you wrote in the text I reached as far as generating the same files that
are in the `Filtered_Data` folder.

Since you did not understand what I meant, I will give you an example of
what I was hoping to see, and what I think most users would appreciate 
when you write documentation of your code. 

The instructions I wanted to see were as simple as:

---------- example instructions begin ---------------------------------------------------------------------

In order to allow the code to run on your system:

1. modify the R code in
`Filtered_Data/Filtered_data_script.R`:

  1.1 Change the path to the Data.xlsx file in line 16 and 17 match the location 
of the `Data.xlsx` file in your system. Example:

```R
UmeaData= read_xlsx("/yourfolder/inputfiles/Data.xlsx", sheet="Umea")
```

  1.2 Change the paths to the output files in lines 447-450 to match the
   desired output path on your system. Example:

```R
write.table(UMEA_LESS,"/yourfolder/outputfiles/UMEA_LESS_HOURS")
```

2. In order to run the R code, select all the code an click "Run".

---------- example instructions end ---------------------------------------------------------------------

Then reading your README.md section "5. Data filtered output" it says:

> To obtain the .txt file filtered for using it into root, we used the library "writexl" and the function write.table.

But I do not understand if I am supposed to write such R code, or it's already there.

Looking inside the source of for example `first_graph_Falsterbo.C` line 26 https://github.com/edutr98/MNXB01-TEAMF/blob/c165730f1acc51fbb77b4282d1398b8882e62563/code/first_graph_Falsterbo.C#L26 
it needs a file `Falsterbo_final.txt` and I don't understand where to get that.

The files generated at the above steps are many (not one), and they do not have any .txt extension.

Reading you new README file I also seem to understand that some additional xlsx modification has been done on the _Final_ files generated above (which are obviously _not final yet?_) and this will yield to more files called `"Falsterbo_GREATER_2", "Falsterbo_LESS_2", "Umeå_GREATER_2", "Umeå_LESS_2"`
of which I see no trace on the git repository.

My guess is that when you write

> Then, it was possible to make the two complete files suitable for all the plots, called "Umeå_final" and "Falsterbo_final".

You actually meant that you **merged** in some *unexplained* way the files 
`"Falsterbo_GREATER_2", "Falsterbo_LESS_2"` into `Falsterbo_final.txt`
and
`"Umeå_GREATER_2", "Umeå_LESS_2"` into `UMEA_FINAL.txt`

So at the end of the day, I still have no idea how to generate your graphs.

Maybe the simplest thing would have been to upload the resulting `.txt` files after the `xlsx` changes so at least I would have had an idea of what they contain. But actually there is no need to do that at this point. I think what you did so far is enough.

### Conclusion

I am very sorry but I already spent enough time evaluating this project, I cannot give you more time. I will grade what you currently submitted.

Here's some advice for your future software projects, this is nothing that you have to do now, but it's just for the future.

- Avoid describing algorithms or choices you made in such detail in a `README` file. These are better described in a technical document  or in this case in the project report. Do not describe choices in such document, this is an operative manual, not a scientific paper.  Your R code is commented enough for someone to understand what it does, it is not needed to have such detail in the `README.md`.

- In the `README.md` file or equivalent, provide users with a brief introduction of what the code does and the **practical actions to do** in order to run the code. 
   - since it is a `.md` file, please use `md` syntax, in this case you can benefit of github extended md features: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/about-writing-and-formatting-on-github
  
- Provide the users with all possible files needed to run the code; if these need to be generated, provide a clear practical description of the steps of how the user can generate them, which is not the same as how you generated them. It's an operational description. 
  - Additionally, provide **examples of input and output files** so at least the user knows what they should look like.
